# Generated by Django 2.0.5 on 2018-05-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monumentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=20)),
                ('nombre_texto', models.CharField(max_length=100)),
                ('descripcion_texto', models.CharField(max_length=300)),
                ('img_old', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
